## Spring 配置
spring:
  ################ Redis 基础配置 ##############
  redis:
    host: 127.0.0.1 #Redis 地址
    port: 6379      #Redis 端口 默认 6379
    password:       #Redis 密码 默认空
    database: 0     #Redis 数据库索引
    timeout: 2000   #Redis 链接超时时间
    ################ Redis 线程池设置 ##############
    lettuce:
      pool:
        max-active: -1 #Redis 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   #Redis 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    #Redis 连接池中的最大空闲连接
        min-idle: 0    #Redis 连接池中的最小空闲连接
  ################ Redis 基础配置完毕 ##############
  datasource:
    url: jdbc:mysql://47.106.218.109:3306/frame?useUnicode=true&characterEncoding=utf8
    username: zy
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

## 服务器 配置
server:
  port: 8099 #端口号
  servlet:
    context-path: /api #设置通过 http://ip:port/api/ 来访问项目